from typing import Callable, Optional

from core.project_context import ProjectContext
from services.vc_service import VCService


class VCPipeline:
    """
    A pipeline dedicated to applying emotional coloring (Voice Conversion)
    to a chapter's worth of synthesized audio files.
    """

    def __init__(self, vc_service: VCService):
        self.vc_service = vc_service

    def run(self, context: ProjectContext, progress_callback: Optional[Callable[[float, str], None]] = None):
        """
        Executes the voice conversion process for a given chapter.
        """

        def update_progress(progress: float, message: str):
            print(message)
            if progress_callback:
                progress_callback(progress, message)

        update_progress(0.0,
                        f"\n{'=' * 80}\n🚀 STARTING VOICE CONVERSION PIPELINE for chapter {context.chapter_id} 🚀\n{'=' * 80}")

        try:
            # 1. Load the scenario
            update_progress(0.05, "--- Step 1: Loading scenario data ---")
            scenario = context.load_scenario()
            if not scenario:
                update_progress(1.0, f"❌ CRITICAL: Scenario file not found for {context.chapter_id}. Aborting.")
                return
            update_progress(0.1, "   -> Scenario loaded successfully.")

            # 2. Process each entry
            update_progress(0.1, "\n--- Step 2: Applying emotions ---")
            total_entries = len(scenario.entries)
            processed_count = 0

            # Lazy load the VC model only when it's actually needed
            vc_model = None

            for i, entry in enumerate(scenario.entries):
                progress = 0.1 + (0.9 * (i / total_entries))
                entry_id = i + 1
                update_progress(progress, f"   -> Processing entry {entry_id}/{total_entries}...")

                # We only process entries with a specific emotion that is not neutral
                if not entry.emotion or entry.emotion.lower() in ["нейтрально", "neutral", "none"]:
                    update_progress(progress, f"      -> ⏩ Skipping neutral/no-emotion entry.")
                    continue

                # Find the source audio file generated by the TTS pipeline
                audio_filename = f"chap_{context.chapter_id}_entry_{entry_id}.wav"
                source_audio_path = context.get_audio_output_dir() / audio_filename

                if not source_audio_path.exists():
                    update_progress(progress, f"      -> ⚠️ Source audio not found: {audio_filename}. Skipping.")
                    continue

                # Find a suitable reference audio for the emotion
                reference_wav_path = self.vc_service.find_reference_wav_for_emotion(entry.emotion)

                if not reference_wav_path:
                    update_progress(progress,
                                    f"      -> ⚠️ No reference sample found for emotion '{entry.emotion}'. Skipping.")
                    continue

                update_progress(progress,
                                f"      -> Emotion: '{entry.emotion}'. Applying style from: {reference_wav_path.name}")

                # Load the model only on the first use
                if vc_model is None:
                    vc_model = self.vc_service.get_vc_model()
                    if not vc_model:
                        update_progress(1.0, "      -> ❌ CRITICAL: Could not load VC model. Aborting.")
                        return

                try:
                    # Perform the conversion and overwrite the source file
                    vc_model.voice_conversion_to_file(
                        source_wav=str(source_audio_path),
                        target_wav=str(reference_wav_path),
                        file_path=str(source_audio_path)
                    )
                    update_progress(progress, f"      -> ✅ Emotion successfully applied to {audio_filename}")
                    processed_count += 1
                except Exception as e:
                    update_progress(progress, f"      -> ❌ ERROR during voice conversion for {audio_filename}: {e}")

            update_progress(1.0,
                            f"\n{'=' * 80}\n🎉 VOICE CONVERSION COMPLETED! Emotions applied to {processed_count} files.\n{'=' * 80}")

        except Exception as e:
            update_progress(1.0, f"❌ CRITICAL ERROR in VC pipeline: {e}")
            import traceback
            traceback.print_exc()
