import json
import logging
from typing import Optional

from core.project_context import ProjectContext
from utils import file_utils
from utils.setup_logging import setup_logging

logger = logging.getLogger(__name__)


def init_manifest(
        book_name: str,
        known_title: Optional[str] = None,
        known_author: Optional[str] = None
):
    """
    Создает или обновляет manifest.json.
    Использует ProjectContext для определения путей.
    """
    logger.info(f"🏁 ЗАПУСК ИНИЦИАЛИЗАЦИИ МАНИФЕСТА: '{book_name}'")

    context = ProjectContext(book_name=book_name)

    book_src_dir = context.book_dir
    output_dir = context.book_output_dir
    manifest_path = context.manifest_file

    logger.info(f"📁 Путь к исходникам (INPUT): {book_src_dir}")
    logger.info(f"📁 Путь к результатам (OUTPUT): {output_dir}")

    if not book_src_dir.exists():
        logger.error(f"❌ ПАПКА НЕ НАЙДЕНА: {book_src_dir}")
        logger.error("Убедитесь, что файлы книги находятся в правильной директории.")
        return

    output_dir.mkdir(parents=True, exist_ok=True)

    logger.info("🔎 Сканирование файловой структуры...")

    chapter_paths = file_utils.get_all_chapters(book_src_dir)

    if not chapter_paths:
        logger.warning("⚠️ Внимание: В папке книги не найдено текстовых файлов (chapter_*.txt)!")
    else:
        logger.info(f"✅ Найдено файлов глав: {len(chapter_paths)}")
        logger.debug(f"Первый найденный файл: {chapter_paths[0].name}")

    structure = []
    logger.info("⚙️ Сборка структуры глав...")

    for idx, path in enumerate(chapter_paths, 1):
        try:
            vol, chap = file_utils.parse_vol_chap_from_path(path)

            chapter_ctx = ProjectContext(book_name, vol, chap)
            chapter_id = chapter_ctx.chapter_id

            status = "draft"
            status_reason = "только текст"

            if chapter_ctx.chapter_audio_dir.exists() and any(chapter_ctx.chapter_audio_dir.iterdir()):
                status = "audio_ready"
                status_reason = "аудио есть"
            elif chapter_ctx.scenario_file.exists():
                status = "scenario_ready"
                status_reason = "сценарий есть"

            display_title = f"Глава {chap}"
            if vol > 1:
                display_title += f" (Том {vol})"

            structure.append({
                "order": idx,
                "id": chapter_id,
                "title": display_title,
                "src_dir": chapter_id,
                "status": status
            })

            if idx == 1 or idx == len(chapter_paths):
                logger.debug(f"   -> Глава {idx}: {chapter_id} [{status}] ({status_reason})")

        except Exception as e:
            logger.error(f"❌ Ошибка обработки пути {path}: {e}")

    logger.info("📝 Подготовка метаданных...")

    current_meta = {}
    if manifest_path.exists():
        logger.info(f"📂 Найден существующий манифест. Читаем данные...")
        try:
            old_manifest = json.loads(manifest_path.read_text("utf-8"))
            current_meta = old_manifest.get("meta", {})
            logger.info(f"   -> Текущее название в файле: '{current_meta.get('title')}'")
        except Exception as e:
            logger.error(f"❌ Ошибка чтения старого манифеста: {e}")

    final_title = current_meta.get("title") or known_title or "Название книги (измените в manifest.json)"
    final_author = current_meta.get("author") or known_author or "Автор (измените в manifest.json)"

    if final_title == "Название книги (измените в manifest.json)":
        logger.warning("⚠️ Используется дефолтное название книги! (Данные не найдены)")

    new_meta = {
        "title": final_title,
        "author": final_author,
        "version": current_meta.get("version", "1.0"),
        "total_duration_ms": current_meta.get("total_duration_ms", 0)
    }

    new_manifest = {
        "project_id": book_name,
        "meta": new_meta,
        "structure": structure,
        "config": {
            "notes": "Generated by init_manifest.py",
            "last_run_log": f"Found {len(structure)} chapters"
        }
    }

    if manifest_path.exists() and "config" in old_manifest:
        merged_config = new_manifest["config"]
        merged_config.update(old_manifest.get("config", {}))
        new_manifest["config"] = merged_config

    manifest_path.write_text(json.dumps(new_manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    logger.info("-" * 40)
    logger.info(f"💾 МАНИФЕСТ СОХРАНЕН: {manifest_path}")
    logger.info(f"   📚 Книга: {final_title}")
    logger.info("-" * 40)


if __name__ == "__main__":
    setup_logging()
    init_manifest("kapitanskaya-dochka")
